"""Anti-drift contract: `docs/reference/attributes.md` == the generator's OWN output.

The attribute reference (authoring layer D12) is generated from the framework registry schemas
by `pipeline.attrdoc`. This test keeps the committed page HONEST by regenerating it in memory and
asserting byte-for-byte equality — so a schema `definition:` (or type/default/version) edited
WITHOUT running `pipeline docs attributes` fails loudly in CI, exactly like the `clients.md`
wire-vocabulary contract (`tests/test_clients_doc_contract.py`).

It also pins the two structural guarantees the generator makes:
  - **Framework-only** (rule 4, §10): the documented collection set is exactly
    `set(lint.REGISTRY_ROOTS)`; the generator never walks `iter_lint_collections`, so a
    schema-shaped directory under `instance/` or `workspaces/` can never leak into the public doc.
  - **Zero-attribute collections render** (not crash): `output-types` (`attributes: {}`) is
    documented with an explicit "no attributes" line.
"""

from __future__ import annotations

import re
from pathlib import Path

from pipeline import attrdoc, lint
from pipeline.layout import registry_dir
from pipeline.schema import SCHEMA_FILENAME

_DOC = attrdoc.framework_root() / attrdoc.DOC_RELPATH

#: A true instance-file / scope-path leak: an `instance/`|`workspaces/` path, or the `x-` instance
#: id prefix at a token boundary. Deliberately boundary-aware so it does NOT false-match "x-" inside
#: an ordinary word (e.g. "Syntax-highlighting" in framework prose).
_LEAK_RE = re.compile(r"workspaces/|instance/|(?:^|[^A-Za-z0-9])x-[a-z]", re.MULTILINE)


def _mirror_framework_schemas(dst: Path) -> None:
    """Copy every framework registry `_schema.yaml` into `dst` (a full generatable root)."""
    src_root = attrdoc.framework_root()
    for name in lint.REGISTRY_ROOTS:
        target = registry_dir(dst, name) / SCHEMA_FILENAME
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            (registry_dir(src_root, name) / SCHEMA_FILENAME).read_text(encoding="utf-8"),
            encoding="utf-8",
        )


# --- The load-bearing byte-equality contract -----------------------------------------------------


def test_attributes_doc_regenerates_identically() -> None:
    """The committed doc IS the generator's output — regenerating changes nothing."""
    committed = _DOC.read_text(encoding="utf-8")
    assert attrdoc.render_attributes_doc() == committed, (
        "docs/reference/attributes.md is stale — run `pipeline docs attributes` and commit the "
        "result (a schema `definition:`/type/default/version changed without regenerating)"
    )


def test_render_is_deterministic() -> None:
    """No clock/env/cwd: two renders of the same schemas are byte-identical."""
    assert attrdoc.render_attributes_doc() == attrdoc.render_attributes_doc()


def test_doc_has_generated_header_first_line() -> None:
    committed = _DOC.read_text(encoding="utf-8")
    assert committed.startswith(attrdoc.GENERATED_HEADER + "\n")
    assert "run `pipeline docs attributes`" in attrdoc.GENERATED_HEADER


# --- Framework-only: the S2-leak guard -----------------------------------------------------------


def test_attributes_doc_walks_registry_roots_only() -> None:
    """The documented collection set is exactly `set(lint.REGISTRY_ROOTS)` — never the
    `instance/`+`workspaces/` superset that `iter_lint_collections` would visit."""
    documented = {name for name, _ in attrdoc.iter_documented_schemas()}
    assert documented == set(lint.REGISTRY_ROOTS)
    for scope in lint.EXTRA_SCOPE_DIRS:  # instance, users
        assert scope not in documented


def test_doc_carries_no_instance_or_client_leak() -> None:
    """The generated bytes carry no `instance/`/`workspaces/` path and no `x-` instance id."""
    committed = _DOC.read_text(encoding="utf-8")
    hit = _LEAK_RE.search(committed)
    assert hit is None, f"attributes.md leaked a non-framework token: {hit.group(0)!r}"


def test_generator_ignores_instance_and_workspace_schemas(tmp_path, monkeypatch) -> None:
    """A schema-shaped dir under `instance/` and `users/` (the §23 client re-home) is IGNORED by
    the generator even though `iter_lint_collections` surfaces it — proving the framework-only
    walk is structural."""
    # One real registry root (a non-empty generatable set under the narrowed REGISTRY_ROOTS).
    registry_dir(tmp_path, "formats").mkdir()
    (registry_dir(tmp_path, "formats") / SCHEMA_FILENAME).write_text(
        (registry_dir(attrdoc.framework_root(), "formats") / SCHEMA_FILENAME).read_text(
            encoding="utf-8"
        ),
        encoding="utf-8",
    )
    # The exact leak surface: registry-shaped dirs under instance/ and the §23 client re-home
    # users/<user>/workspaces/<client>/.
    for scope, dim in (
        ("instance", "leaky-a"),
        ("users/some-user/workspaces/client-one", "leaky-b"),
    ):
        leaf = tmp_path / scope / dim
        leaf.mkdir(parents=True)
        (leaf / SCHEMA_FILENAME).write_text("schema_version: 1\nattributes: {}\n", encoding="utf-8")

    monkeypatch.setattr(lint, "REGISTRY_ROOTS", ("formats",))

    documented = {name for name, _ in attrdoc.iter_documented_schemas(tmp_path)}
    assert documented == {"formats"}
    # iter_lint_collections WOULD surface the leaky dirs — the divergence is the whole point.
    leaked = {p.name for p in lint.iter_lint_collections(tmp_path)}
    assert {"leaky-a", "leaky-b"} <= leaked
    assert not ({"leaky-a", "leaky-b"} & documented)


# --- Zero-attribute collections render (no crash) ------------------------------------------------


def test_attributes_doc_handles_zero_attribute_collection() -> None:
    """`output-types` is `attributes: {}` — it must render a documented section, not crash."""
    schemas = dict(attrdoc.iter_documented_schemas())
    assert "output-types" in schemas
    assert schemas["output-types"].attributes == {}

    doc = attrdoc.render_attributes_doc()
    header = "## `output-types` — schema_version 1"
    assert header in doc
    section = doc.split(header, 1)[1].split("\n## ", 1)[0]
    assert "No attributes" in section


# --- The drift guard BITES (an un-regenerated definition edit fails) ------------------------------


def test_unregenerated_definition_edit_fails(tmp_path) -> None:
    """Edit a `definition:` in a mirrored schema set WITHOUT regenerating → the render diverges
    from its own baseline — exactly the failure `test_..._regenerates_identically` raises."""
    _mirror_framework_schemas(tmp_path)
    baseline = attrdoc.render_attributes_doc(tmp_path)
    assert attrdoc.render_attributes_doc(tmp_path) == baseline  # round-trips against its source

    fmt = registry_dir(tmp_path, "formats") / SCHEMA_FILENAME
    original = fmt.read_text(encoding="utf-8")
    anchor = "Optional ORDERED list of named intra-genre sub-outputs"
    assert anchor in original, "fixture anchor drifted from formats/_schema.yaml — update the test"
    fmt.write_text(original.replace(anchor, "EDITED " + anchor, 1), encoding="utf-8")

    regenerated = attrdoc.render_attributes_doc(tmp_path)
    assert regenerated != baseline, "the drift guard did NOT bite an un-regenerated definition edit"
    assert "EDITED " + anchor in regenerated
